name: 'Remove Polaris Application'

on:
  workflow_dispatch:
    inputs:
      app_env: 
        description: 'Name of environment, relates to cloud provider, e.g. "aws"'
        required: true
      app_id: 
        description: 'Application ID'
        required: true
      app_config:
        description: 'Application config JSON'
        required: true

env:
  TF_VAR_app_id: ${{ github.event.inputs.app_id }}
  TF_VAR_app_config: ${{ github.event.inputs.app_config }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TF_DIR: terraform/${{ inputs.app_env }}
      SCRIPT_DIR: scripts
    
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
        role-duration-seconds: 1200
        aws-region: ${{ secrets.AWS_REGION }}

    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Retrieve State S3 Bucket
      id: setup_resources
      run: bash create_state_bucket.sh ${{ github.event.inputs.app_id }}
      working-directory: ${{ env.SCRIPT_DIR }}

    - name: Terraform Init
      run: terraform init  -backend-config="bucket=${{ steps.setup_resources.outputs.bucket_name}}" -backend-config="dynamodb_table=${{ steps.setup_resources.outputs.table_name }}"
      working-directory: ${{ env.TF_DIR }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{ env.TF_DIR }}

    - name: Terraform Plan Destroy
      run: terraform plan -destroy
      working-directory: ${{ env.TF_DIR }}

    - name: Terraform Apply Destroy
      run: terraform destroy -auto-approve
      working-directory: ${{ env.TF_DIR }}

    - name: Cleanup S3 Bucket and DynamoDB Table
      run: bash cleanup_state_bucket.sh  ${{ github.event.inputs.app_id }}
      working-directory: ${{ env.SCRIPT_DIR }}